#!/bin/bash

qemu-system-x86_64 -enable-kvm -m 8192 -cpu host \
-net nic -net user,hostfwd=tcp::5555-:22 \
-smp 2,sockets=1,cores=2,threads=1 \
-soundhw hda \
-vga qxl \
-spice port=5930,disable-ticketing \
-drive file=/home/benny/VMs/UMAutonomy.img,format=raw,if=virtio,cache=none \
