#!/bin/bash

bridge=br0
tap=tap0
ip=192.168.1.125

ip link add name $bridge type bridge
ip link set $bridge up

ip link set $1 up

ip link set $1 master $bridge

ip tuntap add dev $tap mode tap user benny group benny

ip link set $tap master $bridge

ip addr flush dev br0

ip route flush dev br0

ip addr add $ip/24 broadcast 192.168.1.255 dev br0

ip route add default via 192.168.1.1
