#!/bin/bash

#######################################################################################
# This script is designed to automatically detect and display to one external monitor #
# it may be updated later to support multiple monitors if I have a use for it.        #
# This script now has a dependency on jq to operate properly due to a bspwm update    #
#######################################################################################
export DISPLAY=:0
export XAUTHORITY=/home/benny/.Xauthority

laptopscreen=eDP1
externalscreen=DP1-1
direction=left-of
#lidstate=$(cat /proc/acpi/button/lid/LID0/state | awk '{print $2}')
lidstate=true

if [ $lidstate == "open" ]
then
    echo "Using internal monitor"
    xrandr --output $laptopscreen --auto
    xrandr --output $externalscreen --off
    bspc monitor $externalscreen -a Desktop

    for i in {1..6}
    do
        bspc desktop $i -m $laptopscreen
    done
    
    bspc monitor $externalscreen -r

    # Cleanup default desktops
    bspc wm -a temp 0x0+0+0
    for i in $(bspc query -D | grep Desktop)
    do 
        bspc desktop $i -m temp
    done
    bspc monitor temp -r

    bspc monitor $laptopscreen -o 1 2 3 4 5 6
else
    echo "Using external monitor"
    xrandr --output $externalscreen --auto
    xrandr --output $laptopscreen --off
    bspc monitor $laptopscreen -a Desktop

    for i in {1..6}
    do
        bspc desktop $i -m $externalscreen
        echo "MOVING DESKTOP $i to $externalscreen"
    done

    bspc monitor $laptopscreen -r 
fi

# Cleanup default desktops
bspc wm -a temp 0x0+0+0
for i in $(bspc query -D)
do 
    currentdesktop=$(bspc query -T -d $i | jq .name | tr -d '"')
    if grep -q Desktop <<< $currentdesktop
    then
        echo "Deleting $currentdesktop"
        bspc desktop $i -m temp
    fi
done
bspc monitor temp -r
